---
- name: Remove python to get latest
  apt: name="python2.7" state="absent"

- name: Install build essentials packages and others
  apt:
    name: "{{ item }}"
    state: present
    force: yes
  with_items:
    - linux-generic
    - python-minimal
    - aptitude
    - autoconf
    - binutils-doc
    - bison
    - build-essential
    - flex
    - gettext
    - ncurses-dev
    - imagemagick
    - libmagickwand-dev
    - openssl
    - acl # for ansible 2.2 become user unprivileged

- name: Install python setuptools
  apt: name=python-setuptools update-cache=yes cache_valid_time=86400

- name: Add repository for latest python 2.7
  apt_repository: repo="ppa:jonathonf/python-2.7" state=present

- name: Update python
  apt: name="python2.7" state="present" update_cache=yes

- name: Install upstart-sysv for ubuntu 16.04+ which comes with only systemd
  apt:
    name: "upstart-sysv"
    state: present
    force: yes
  when: ansible_distribution_version != '14.04'

- name: Remove ruby1.9.3.
  apt:
    name: ruby1.9.3
    state: absent
    force: yes

- name: "Install pip"
  shell: |
    cd /tmp;
    rm get-pip.py;
    wget https://bootstrap.pypa.io/get-pip.py;
    python get-pip.py
  become: yes
  # easy_install: name=pip

# - pip: when python 2.6.x is too low Install packages for SNI verified download on http
#   pip:
#     name: "{{ item }}"
#   with_items:
#     - urllib3
#     - pyopenssl
#     - ndg-httpsclient
#     - pyasn1

- name: "Install cli53"
  pip: name=cli53

- name: Install boto
  pip: name=boto version=2.43.0 state=present

- name: Install boto3
  pip: name=boto3 state=latest
