---

language: python
python: "2.7"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq python-apt python-pycurl git
 - git clone https://github.com/Stouts/Stouts.nginx roles/Stouts.nginx
 - git clone https://github.com/Stouts/Stouts.redis roles/Stouts.redis
 - git clone https://github.com/Stouts/Stouts.python roles/Stouts.python
install:
  - pip install ansible>=1.6.0
script:
  # Prepare tests
  - echo localhost > inventory

  # Check syntax
  - ansible-playbook --syntax-check -i inventory test.yml

  # First run
  - ansible-playbook -i inventory test.yml --connection=local --sudo

  # First run
  - ansible-playbook -i inventory test.yml --connection=local --sudo

  # Second run Idempotence test
  - >
    ansible-playbook -i inventory test.yml --connection=local --sudo
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  - sudo rm -f /etc/nginx/sites-enabled/default
  - sudo /etc/init.d/nginx restart
  - curl localhost || exit 1
 
sentry_home: /home/travis/build/sentry
sentry_cache_backend: ""
sentry_broker_url: ""
sentry_buffer: ""
python_pip_latest:
  - virtualenv
