- hosts: all
  roles:
  - Stouts.redis
  - Stouts.nginx
  - Stouts.python
  tasks:
    - include: tasks/main.yml
  handlers:
    - include: handlers/main.yml
  vars_files:
    - defaults/main.yml
    - .travis.yml
  vars:
    redis_update_kernel: no
