---
# tasks file for aws.vpc-create

- name: create VPC
  ec2_vpc_net:
    name: "{{ outer_item.vpc_name }}"
    cidr_block: "{{ outer_item.cidr_block }}"
    region: "{{ outer_item.region }}"
    state: "present"
  register: vpc
  tags:
    - vpc

- name: set VPC ID in variable
  set_fact: 
    vpc_id: "{{ vpc.vpc.id }}"
  tags:
    - vpc

- debug: msg="{{ vpc_id }}"
  tags:
    - vpc

- name: create igw for VPC - {{ vpc_id }}
  ec2_vpc_igw:
    vpc_id: "{{ vpc_id }}"
    region: "{{ outer_item.region }}"
    state: "present"
  register: vpc_igw
  tags:
    - igw

- name: create public subnet into VPC - {{ vpc_id }}
  ec2_vpc_subnet:
    state: present
    vpc_id: "{{ vpc_id }}"
    region: "{{ outer_item.region }}"
    cidr: "{{ item.cidr }}"
    map_public: yes
    az: "{{ item.az }}"
    resource_tags:
      name: "{{ item.name }}"
  with_items: "{{ outer_item.subnets }}"
  register: subnet
  tags:
    - subnet