---
# tasks file for aws.vpc-create

- name: create VPC
  ec2_vpc_net:
    name: "{{ outer_item.vpc_name }}"
    cidr_block: "{{ outer_item.cidr_block }}"
    region: "{{ outer_item.region }}"
    state: "present"
  register: vpc
  tags:
    - vpc
    - igw
    - public_subnet
    - route_table

- name: set VPC ID in variable
  set_fact: 
    vpc_id: "{{ vpc.vpc.id }}"
  tags:
    - vpc
    - igw
    - public_subnet
    - route_table

- debug: msg="{{ vpc_id }}"
  tags:
    - vpc
    - igw
    - public_subnet
    - route_table

- name: create igw for VPC - {{ vpc_id }}
  ec2_vpc_igw:
    vpc_id: "{{ vpc_id }}"
    region: "{{ outer_item.region }}"
    state: "present"
  register: igw
  tags:
    - igw

- name: set IGW ID in variable
  set_fact: 
    igw_id: "{{ igw.gateway_id }}"
  tags:
    - igw

- debug: msg="{{ igw_id }}"
  tags:
    - igw

- name: create public subnet into VPC - {{ vpc_id }}
  ec2_vpc_subnet:
    state: present
    vpc_id: "{{ vpc_id }}"
    region: "{{ outer_item.region }}"
    cidr: "{{ item.cidr }}"
    map_public: yes
    az: "{{ item.az }}"
    resource_tags:
      Name: "{{ item.name }}"
  with_items: "{{ outer_item.subnets }}"
  register: subnet
  tags:
    - public_subnet

- name: Create route table
  ec2_vpc_route_table:
    vpc_id: "{{ vpc_id }}"
    region: "{{ outer_item.region }}"
    subnets: "{{ item.name }}"
    # subnets:
    #   - "{{ subnet.subnet.id }}"
    routes: "{{ item.routes }}"
    tags:
      name: "{{ item.name }}"
  with_items: "{{ outer_item.subnets }}"
  register: route_table
  tags:
    - route_table