---
# tasks file for aws.vpc-create

- name: Create VPC
  ec2_vpc_net:
    name: "{{ outer_item.vpc_name }}"
    cidr_block: "{{ outer_item.cidr_block }}"
    region: "{{ outer_item.region }}"
    state: "present"
  register: vpc
  tags:
    - vpc

- name: Set VPC ID in variable
  set_fact: 
    vpc_id: "{{ vpc.vpc.id }}"
  tags:
    - vpc

- debug: msg="{{ vpc_id }}"
  tags:
    - vpc

- name: Create Internet Gateway for VPC
  ec2_vpc_igw:
    vpc_id: "{{ vpc_id }}"
    state: "present"
  register: vpc_igw
  tags:
    - vpc