# ansible-playbook -i hosts aws-vpc-create.yml
# ansible-playbook -i hosts aws-vpc-create.yml --tags "vpc"
---
- name: Create vpc in aws
  hosts: localhost
  connection: local
  gather_facts: False

  vars_files:
    - vars/dev/vpc.yml

  tasks:
    - name: create vpc
      include_role:
        name: aws.vpc-create
      with_items:
        - { vpc_name: "{{ dev_vpc_name }}", cidr_block: "{{ dev_cidr_block }}", region: "{{ dev_aws_region }}" }
      loop_control:
        loop_var: outer_item
      tags:
        - vpc