
# ansible-playbook --inventory-file inventory/hosts-localhost -e target_vpc=dev aws-bastion-target-vpc-instance-create.yml --tags "security_group"
# put sg_id in vars/{{ target_vpc }}/bastion.yml
# 
---
- name: Create bastion EC2 instance in AWS
  hosts: localhost
  connection: local
  gather_facts: False

  vars_files:
    - vars/security_rules.yml
    - vars/{{ target_vpc }}/bastion.yml

  roles:
    - { role: aws.ec2-instance-create }

# - name: Wait for port 22 to be ready
#   hosts: managed-hosts
#   gather_facts: False

#   vars:
#     - ansible_ssh_host: managed-hosts

#   tasks:
#     - local_action: wait_for port=22 host="{{ ansible_ssh_host }}" search_regex=OpenSSH delay=60