# ansible-playbook -i hosts aws-vpc-create.yml --tags "vpc"
# ansible-playbook -i hosts aws-vpc-create.yml --tags "igw"
# put igw_id in vars/{{ env }}/vpc.yml
# ansible-playbook -i hosts aws-vpc-create.yml --tags "public_subnet"
# ansible-playbook -i hosts aws-vpc-create.yml --tags "route_table"
---
- name: Create vpc in aws
  hosts: localhost
  connection: local
  gather_facts: False

  vars_files:
    - vars/dev/vpc.yml
    - vars/ops/vpc.yml

  tasks:
    - name: create vpc
      include_role:
        name: aws.vpc-create
      with_items:
        - { vpc_name: "{{ dev.vpc_name }}", cidr_block: "{{ dev.cidr_block }}", region: "{{ dev.aws_region }}", subnets: "{{ dev.public_subnets }}" }
        # - { vpc_name: "{{ ops_vpc_name }}", cidr_block: "{{ ops_cidr_block }}", region: "{{ ops_aws_region }}" }
      loop_control:
        loop_var: outer_item
      tags:
        - vpc
        - igw
        - public_subnet
        - route_table