# ansible-playbook -i hosts aws-vpc-network-create.yml
---
- name: Create aws vpc network
  hosts: localhost
  connection: local
  gather_facts: False

  vars_files:
    - vars/dev/vpc.yml

- name: Create VPC
  with_items:
    - { vpc_name: "{{ dev_vpc_name }}", cidr_block: "{{ dev_cidr_block }}", region: "{{ dev_aws_region }}" }
  include_role:
    name: aws.vpc-network
  vars:
    thing: "{{ item }}"