---
- name: Configure sentry
  hosts: "{{ hosts }}"
  become: yes
  remote_user: ubuntu
  gather_facts: true


  pre_tasks:
    - name: 'install python2'
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

  # roles:
  #   - { role: base, tags: [ base ] }
  #   - { role: docker, tags: [ docker ] }

  roles:
    - common
    - python
