# ansible-playbook -i inventory/hosts-sentry -e hosts=all sentry-server-install.yml
---
- name: Configure sentry
  hosts: "{{ hosts }}"
  become: yes
  remote_user: ubuntu
  gather_facts: true

  pre_tasks:
    - name: 'install python2'
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

  roles:
    - common
    - python
    - { role: docker, tags: [ docker ] }
    - { role: nginx, tags: [ nginx ] }
    - { role: sentry, tags: [ sentry ] }
