# ansible-playbook -i hosts sentry-server-configure.yml -u ec2-user -s
---
- name: Configure sentry server
  hosts: localhost
  connection: local
  gather_facts: False
  become: yes

  vars:
    - aws_region: "ap-south-1"

  tasks:
    - name:  launch sentry cloudformation stack
      cloudformation:
        stack_name: "sentry"
        region: "{{ aws_region }}"
        state: "present"
        template: "ec2.yml"
        template_parameters:
          KeyName: "ec2"
          InstanceType: "t2.micro"

    - ec2_remote_facts:
        filters:
          instance-state-name: running
          "tag:Name": sentry_server
        region: "{{ aws_region }}"
      register: instance_details

    - debug: msg="{{ instance_details }}"

    - name: Add instance IP to group
      local_action:
        module: add_host
        hostname: sentry
        name: "{{ instance_details.instances[0].private_ip_address }}"
        groupname: sentry-server
        ansible_ssh_host: "{{ instance_details.instances[0].private_ip_address }}"
        ansible_user: ec2-user
      register: check

    - debug: msg="{{ check }}"

    - name: Wait for port 22 to be ready
      hosts: sentry-server
      gather_facts: False

  tasks:
    - local_action: wait_for port=22 host="{{ ansible_ssh_host }}" search_regex=OpenSSH delay=60

- hosts: sentry-server
  roles:
    - docker
