# ansible-playbook -i hosts sentry-server-configure.yml
---
- name: Configure sentry server
  hosts: localhost
  connection: local
  gather_facts: False

  vars_files:
    - vars/sentry.yml

  tasks:
    - name:  launch sentry cloudformation stack
      cloudformation:
        stack_name: "{{ cloudformation_stack_name }}"
        state: "present"
        region: "{{ aws_region }}"
        disable_rollback: true
        template: "{{ cloudformation_template }}"
        template_parameters:
          KeyName: "{{ ssh_key_pair_name }}"
          InstanceType: "{{ ec2_instance_type }}"
      register: stack

    - debug: msg="{{ stack }}"

    - ec2_remote_facts:
        filters:
          instance-state-name: running
          "tag:Name": sentry
        region: "{{ aws_region }}"
      register: ec2

    - debug: msg="{{ ec2 }}"

    - name: Add the newly created host so that we can further contact it
      add_host:
        name: "{{ item.public_ip_address }}"
        groups: sentry
      with_items: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_ip_address }}"
        port: 22
        state: started
      with_items: "{{ ec2.instances }}"

- hosts: sentry
  remote_user: ubuntu
  become: yes
  gather_facts: yes

  pre_tasks:
    - name: 'install python2'
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

  roles:
    - common
    - python
    - { role: docker, tags: [ docker ] }
    - { role: nginx, tags: [ nginx ] }
    - { role: sentry, tags: [ sentry ] }
