---
- name: Configure sentry
  hosts: "{{ hosts }}"
  become: yes
  remote_user: ubuntu
  gather_facts: no

  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python2.7

  roles:
    - { role: base, tags: [ base ] }
    - { role: docker, tags: [ docker ] }
