# ansible-playbook -i hosts sentry-server-configure.yml -u ubuntu -s
---
- name: Configure sentry server
  hosts: localhost
  connection: local
  gather_facts: False

  vars:
    - aws_region: "ap-south-1"

  tasks:
    - name:  launch sentry cloudformation stack
      cloudformation:
        stack_name: "sentry"
        region: "{{ aws_region }}"
        state: "present"
        template: "ec2.yml"
        template_parameters:
          KeyName: "admin"
          InstanceType: "t2.medium"
      register: stack

    - debug: msg="{{ stack }}"

    - ec2_remote_facts:
        filters:
          instance-state-name: running
          "tag:Name": sentry
        region: "{{ aws_region }}"
      register: ec2

    - debug: msg="{{ ec2 }}"

    - name: Add the newly created host so that we can further contact it
      add_host:
        name: "{{ item.public_ip_address }}"
        groups: sentry
      with_items: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_ip_address }}"
        port: 22
        state: started
      with_items: "{{ ec2.instances }}"

- hosts: sentry
  remote_user: ubuntu
  become: yes
  gather_facts: yes

  pre_tasks:
    - name: 'install python2'
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

  roles:
    - common
    - python
