---
# tasks file for aws.ec2-instance-create

- name: Create EC2 security group
  ec2_group:
    name: "{{ ec2_prefix }}-security-group"
    description: "{{ ec2_prefix }} security group"
    region: "{{ aws_region }}"
    rules: "{{ security_rules.inbound }}"
    vpc_id: "{{ vpc_id }}"
    rules_egress: "{{ security_rules.outbound }}"
  register: security_group
  tags:
    - security_group

- name: Create EC2 instance
  ec2:
    key_name: "{{ ssh_key_name }}"
    region: "{{ aws_region }}"
    group_id: "{{ security_group.group_id }}"
    instance_type: "{{ instance_type }}"
    image: "{{ aws_ami }}"
    wait: yes
    count_tag:
      Name: "{{ ec2_prefix }}"
    instance_tags:
      Name: "{{ ec2_prefix }}"
    exact_count: "{{ instance_count }}"
    vpc_subnet_id: "{{ vpc_subnet_id }}"
    assign_public_ip: "{{ assign_public_ip }}"
  with_items:
    - { name: "{{ ec2_prefix }}" }
  register: ec2
  tags:
    - ec2
    - security_group

- debug: msg="{{ ec2 }}"

# Ansible in-memory inventory, check DevOps_Handbook notes

# - name: Add instance IP to group
#   local_action:
#     module: add_host
#     hostname: "{{ item.item.name }}"
#     name: "{{ item.tagged_instances[0].public_ip }}"
#     groupname: managed-hosts
#     ansible_ssh_host: "{{ item.tagged_instances[0].public_ip }}"
#   with_items: "{{ec2.results}}"
#   when: ec2.results[0].tagged_instances