---
# tasks file for aws.ec2-instance-create

- name: Create EC2 security group
  ec2_group:
    name: "{{ ec2_prefix }}-security-group"
    description: "{{ ec2_prefix }} security group"
    region: "{{ aws_region }}"
    rules: "{{ security_rules.inbound }}"
    vpc_id: "{{ vpc_id }}"
    rules_egress: "{{ security_rules.outbound }}"
  register: security_group
  tags:
    - security_group

- name: Create EC2 instances
  ec2:
    key_name: "{{ ssh_key_name }}"
    region: "{{ aws_region }}"
    group_id: "{{ security_group.group_id }}"
    instance_type: "{{ instance_type }}"
    image: "{{ aws_ami }}"
    wait: yes
    count_tag:
      Name: "{{ ec2_prefix }}"
    instance_tags:
      Name: "{{ ec2_prefix }}"
    exact_count: "{{ instance_count }}"
    vpc_subnet_id: "{{ vpc_subnet_id }}"
    assign_public_ip: "{{ assign_public_ip }}"
  register: ec2
  tags:
    - ec2
    - security_group

# - debug: 
#     msg: {{ec2.instances[0].public_ip}}
#   tags:
#     - ec2


# - name: Add the newly created EC2 instance(s) to the local host group
#   local_action: lineinfile 
#                 path={{ inventory_path }}
#                 regexp={{ item.public_ip }} 
#                 insertafter="[bastion]" line="{{ item.public_ip }} ansible_user=ec2-user"
#   with_items: "{{ ec2.instances }}"

# - name: Wait for SSH to come up
#   local_action: wait_for 
#                 host={{ item.public_ip }} 
#                 port=22 
#                 state=started
#   with_items: "{{ ec2.instances }}"

# - name: Wait for SSH to come up
#   local_action:
#     module: wait_for
#     port: 22
#     host: "{{ ec2.private_ip }}"
#     search_regex: OpenSSH
#     delay: 60