---
# tasks file for aws.instance-ssh-key-pair-create

- name: Create a new EC2 key pair
  ec2_key:
    name: "{{ key_name }}"
    region: "{{ region_name }}"
  register: ec2_key

- name: Save private key locally
  copy: content="{{ ec2_key.key.private_key }}" dest="~/.ssh/{{ key_name }}.pem" mode=0400